version: '3'
services:
  puppeteer:
    image: ghcr.io/puppeteer/puppeteer:latest
    stdin_open: true
    init: true
    working_dir: /home/app
    cap_add:
      - SYS_ADMIN
    volumes:
        - .:/home/app/
    command: ["node", "/home/app/main.js"]
