version: '3'
services:
  puppeteer:
    build:
      dockerfile: Dockerfile
    stdin_open: true
    init: true
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN
    working_dir: /home/app
    volumes:
        - .:/home/app/:rw
    command: ["sh","-c", "node main.js"]
